version: '3.8'

x-airflow-common: &airflow-common
  build:
    context: .
    dockerfile: Dockerfile
  environment: &airflow-environment
    AIRFLOW__CORE__REMOTE_LOGGING: 'False'
    AIRFLOW__CORE__BASE_LOG_FOLDER: '/opt/airflow/logs'
    AIRFLOW__CORE__DAGS_FOLDER: '/opt/airflow/dags'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'False'
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__WEBSERVER__BASE_URL: http://localhost:8080
  env_file:
    - local.env
  restart: always
  volumes:
    - ./dags:/opt/airflow/dags
    - ./db_generator:/opt/airflow/db_generator
    - ./great_expectations:/opt/airflow/great_expectations
    - ./logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins
    - ./profilers:/opt/airflow/profilers

services:
  my_small_dwh:
    image: postgres:13
    environment: &trg-env
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: 5432
    restart: always
    ports:
      - "5432:5432"
    expose:
      - "5432"

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 10s
      retries: 5
      start_period: 5s

  airflow-webserver:
    <<: *airflow-common
    environment:
      <<: *airflow-environment
      AIRFLOW__CORE__EXECUTOR: "LocalExecutor"
      AIRFLOW__CORE__PARALLELISM: 8
      AIRFLOW__CORE__DAG_CONCURRENCY: 8
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    depends_on:
      - postgres
      - my_small_dwh
    command: webserver

  airflow-scheduler:
    <<: *airflow-common
    environment:
      <<: *airflow-environment
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8974/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    depends_on:
      - airflow-webserver
    command: scheduler
